python3 test.py \
--content_path /mnt/c/Dataset/Calli_test \
--style_path /mnt/c/Dataset/style_test \
--name AdaAttN \
--model adaattn \
--dataset_mode unaligned \
--load_size 512 \
--crop_size 512 \
--image_encoder_path checkpoints/vgg_normalised.pth \
--gpu_ids 0 \
--skip_connection_3 \
--shallow_layer
